export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      companies: {
        Row: {
          id: string;
          name: string;
          name_kana: string | null;
          postal_code: string | null;
          address: string | null;
          phone: string | null;
          email: string | null;
          website: string | null;
          logo_url: string | null;
          settings: Json;
          subscription_plan: string;
          subscription_status: string;
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          trial_ends_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          name_kana?: string | null;
          postal_code?: string | null;
          address?: string | null;
          phone?: string | null;
          email?: string | null;
          website?: string | null;
          logo_url?: string | null;
          settings?: Json;
          subscription_plan?: string;
          subscription_status?: string;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          trial_ends_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          name_kana?: string | null;
          postal_code?: string | null;
          address?: string | null;
          phone?: string | null;
          email?: string | null;
          website?: string | null;
          logo_url?: string | null;
          settings?: Json;
          subscription_plan?: string;
          subscription_status?: string;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          trial_ends_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      stores: {
        Row: {
          id: string;
          company_id: string;
          name: string;
          name_kana: string | null;
          postal_code: string | null;
          address: string | null;
          phone: string | null;
          email: string | null;
          business_hours: Json;
          holidays: Json;
          settings: Json;
          is_active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          name: string;
          name_kana?: string | null;
          postal_code?: string | null;
          address?: string | null;
          phone?: string | null;
          email?: string | null;
          business_hours?: Json;
          holidays?: Json;
          settings?: Json;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          name?: string;
          name_kana?: string | null;
          postal_code?: string | null;
          address?: string | null;
          phone?: string | null;
          email?: string | null;
          business_hours?: Json;
          holidays?: Json;
          settings?: Json;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      staff: {
        Row: {
          id: string;
          company_id: string;
          user_id: string | null;
          employee_code: string;
          last_name: string;
          first_name: string;
          last_name_kana: string | null;
          first_name_kana: string | null;
          email: string | null;
          phone: string | null;
          avatar_url: string | null;
          role: string;
          rank: string | null;
          nomination_fee: number;
          hire_date: string | null;
          birth_date: string | null;
          skills: Json;
          settings: Json;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          user_id?: string | null;
          employee_code: string;
          last_name: string;
          first_name: string;
          last_name_kana?: string | null;
          first_name_kana?: string | null;
          email?: string | null;
          phone?: string | null;
          avatar_url?: string | null;
          role?: string;
          rank?: string | null;
          nomination_fee?: number;
          hire_date?: string | null;
          birth_date?: string | null;
          skills?: Json;
          settings?: Json;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          user_id?: string | null;
          employee_code?: string;
          last_name?: string;
          first_name?: string;
          last_name_kana?: string | null;
          first_name_kana?: string | null;
          email?: string | null;
          phone?: string | null;
          avatar_url?: string | null;
          role?: string;
          rank?: string | null;
          nomination_fee?: number;
          hire_date?: string | null;
          birth_date?: string | null;
          skills?: Json;
          settings?: Json;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      staff_stores: {
        Row: {
          id: string;
          staff_id: string;
          store_id: string;
          is_primary: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          staff_id: string;
          store_id: string;
          is_primary?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          staff_id?: string;
          store_id?: string;
          is_primary?: boolean;
          created_at?: string;
        };
      };
      customers: {
        Row: {
          id: string;
          company_id: string;
          customer_code: string;
          last_name: string;
          first_name: string;
          last_name_kana: string | null;
          first_name_kana: string | null;
          email: string | null;
          phone: string | null;
          postal_code: string | null;
          address: string | null;
          birth_date: string | null;
          gender: string | null;
          occupation: string | null;
          memo: string | null;
          referral_source: string | null;
          preferred_staff_id: string | null;
          total_visits: number;
          total_spend: number;
          points_balance: number;
          last_visit_at: string | null;
          privacy_consent: boolean;
          marketing_consent: boolean;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          customer_code: string;
          last_name: string;
          first_name: string;
          last_name_kana?: string | null;
          first_name_kana?: string | null;
          email?: string | null;
          phone?: string | null;
          postal_code?: string | null;
          address?: string | null;
          birth_date?: string | null;
          gender?: string | null;
          occupation?: string | null;
          memo?: string | null;
          referral_source?: string | null;
          preferred_staff_id?: string | null;
          total_visits?: number;
          total_spend?: number;
          points_balance?: number;
          last_visit_at?: string | null;
          privacy_consent?: boolean;
          marketing_consent?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          customer_code?: string;
          last_name?: string;
          first_name?: string;
          last_name_kana?: string | null;
          first_name_kana?: string | null;
          email?: string | null;
          phone?: string | null;
          postal_code?: string | null;
          address?: string | null;
          birth_date?: string | null;
          gender?: string | null;
          occupation?: string | null;
          memo?: string | null;
          referral_source?: string | null;
          preferred_staff_id?: string | null;
          total_visits?: number;
          total_spend?: number;
          points_balance?: number;
          last_visit_at?: string | null;
          privacy_consent?: boolean;
          marketing_consent?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      customer_kartes: {
        Row: {
          id: string;
          customer_id: string;
          hair_type: string | null;
          hair_thickness: string | null;
          hair_volume: string | null;
          scalp_condition: string | null;
          damage_level: string | null;
          gray_hair_percentage: number | null;
          face_shape: string | null;
          skin_tone: string | null;
          lifestyle: string | null;
          styling_preference: string | null;
          allergies: Json;
          medical_conditions: Json;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          customer_id: string;
          hair_type?: string | null;
          hair_thickness?: string | null;
          hair_volume?: string | null;
          scalp_condition?: string | null;
          damage_level?: string | null;
          gray_hair_percentage?: number | null;
          face_shape?: string | null;
          skin_tone?: string | null;
          lifestyle?: string | null;
          styling_preference?: string | null;
          allergies?: Json;
          medical_conditions?: Json;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          customer_id?: string;
          hair_type?: string | null;
          hair_thickness?: string | null;
          hair_volume?: string | null;
          scalp_condition?: string | null;
          damage_level?: string | null;
          gray_hair_percentage?: number | null;
          face_shape?: string | null;
          skin_tone?: string | null;
          lifestyle?: string | null;
          styling_preference?: string | null;
          allergies?: Json;
          medical_conditions?: Json;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      customer_photos: {
        Row: {
          id: string;
          customer_id: string;
          visit_id: string | null;
          photo_type: string;
          photo_url: string;
          thumbnail_url: string | null;
          caption: string | null;
          taken_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          customer_id: string;
          visit_id?: string | null;
          photo_type: string;
          photo_url: string;
          thumbnail_url?: string | null;
          caption?: string | null;
          taken_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          customer_id?: string;
          visit_id?: string | null;
          photo_type?: string;
          photo_url?: string;
          thumbnail_url?: string | null;
          caption?: string | null;
          taken_at?: string;
          created_at?: string;
        };
      };
      color_recipes: {
        Row: {
          id: string;
          customer_id: string;
          visit_id: string | null;
          recipe_name: string;
          base_color: string | null;
          target_color: string | null;
          products: Json;
          mixing_ratio: string | null;
          processing_time: number | null;
          developer_volume: string | null;
          application_notes: string | null;
          result_notes: string | null;
          rating: number | null;
          photos: Json;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          customer_id: string;
          visit_id?: string | null;
          recipe_name: string;
          base_color?: string | null;
          target_color?: string | null;
          products?: Json;
          mixing_ratio?: string | null;
          processing_time?: number | null;
          developer_volume?: string | null;
          application_notes?: string | null;
          result_notes?: string | null;
          rating?: number | null;
          photos?: Json;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          customer_id?: string;
          visit_id?: string | null;
          recipe_name?: string;
          base_color?: string | null;
          target_color?: string | null;
          products?: Json;
          mixing_ratio?: string | null;
          processing_time?: number | null;
          developer_volume?: string | null;
          application_notes?: string | null;
          result_notes?: string | null;
          rating?: number | null;
          photos?: Json;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      perm_recipes: {
        Row: {
          id: string;
          customer_id: string;
          visit_id: string | null;
          recipe_name: string;
          perm_type: string | null;
          rod_sizes: Json;
          winding_pattern: string | null;
          solution_type: string | null;
          processing_time_1: number | null;
          processing_time_2: number | null;
          neutralizer: string | null;
          result_curl_size: string | null;
          result_notes: string | null;
          rating: number | null;
          photos: Json;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          customer_id: string;
          visit_id?: string | null;
          recipe_name: string;
          perm_type?: string | null;
          rod_sizes?: Json;
          winding_pattern?: string | null;
          solution_type?: string | null;
          processing_time_1?: number | null;
          processing_time_2?: number | null;
          neutralizer?: string | null;
          result_curl_size?: string | null;
          result_notes?: string | null;
          rating?: number | null;
          photos?: Json;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          customer_id?: string;
          visit_id?: string | null;
          recipe_name?: string;
          perm_type?: string | null;
          rod_sizes?: Json;
          winding_pattern?: string | null;
          solution_type?: string | null;
          processing_time_1?: number | null;
          processing_time_2?: number | null;
          neutralizer?: string | null;
          result_curl_size?: string | null;
          result_notes?: string | null;
          rating?: number | null;
          photos?: Json;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      menu_categories: {
        Row: {
          id: string;
          company_id: string;
          name: string;
          description: string | null;
          icon: string | null;
          color: string | null;
          sort_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          name: string;
          description?: string | null;
          icon?: string | null;
          color?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          name?: string;
          description?: string | null;
          icon?: string | null;
          color?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      menus: {
        Row: {
          id: string;
          company_id: string;
          category_id: string | null;
          code: string;
          name: string;
          description: string | null;
          base_price: number;
          price_short: number | null;
          price_medium: number | null;
          price_long: number | null;
          duration_minutes: number;
          is_set_menu: boolean;
          set_items: Json;
          tax_rate: number;
          is_ticket_eligible: boolean;
          is_coupon_eligible: boolean;
          is_nomination_required: boolean;
          sort_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          category_id?: string | null;
          code: string;
          name: string;
          description?: string | null;
          base_price: number;
          price_short?: number | null;
          price_medium?: number | null;
          price_long?: number | null;
          duration_minutes?: number;
          is_set_menu?: boolean;
          set_items?: Json;
          tax_rate?: number;
          is_ticket_eligible?: boolean;
          is_coupon_eligible?: boolean;
          is_nomination_required?: boolean;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          category_id?: string | null;
          code?: string;
          name?: string;
          description?: string | null;
          base_price?: number;
          price_short?: number | null;
          price_medium?: number | null;
          price_long?: number | null;
          duration_minutes?: number;
          is_set_menu?: boolean;
          set_items?: Json;
          tax_rate?: number;
          is_ticket_eligible?: boolean;
          is_coupon_eligible?: boolean;
          is_nomination_required?: boolean;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      processes: {
        Row: {
          id: string;
          company_id: string;
          code: string;
          name: string;
          description: string | null;
          default_duration_minutes: number;
          productivity_weight: number;
          sort_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          code: string;
          name: string;
          description?: string | null;
          default_duration_minutes?: number;
          productivity_weight?: number;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          code?: string;
          name?: string;
          description?: string | null;
          default_duration_minutes?: number;
          productivity_weight?: number;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      menu_processes: {
        Row: {
          id: string;
          menu_id: string;
          process_id: string;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          menu_id: string;
          process_id: string;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          menu_id?: string;
          process_id?: string;
          sort_order?: number;
          created_at?: string;
        };
      };
      products: {
        Row: {
          id: string;
          company_id: string;
          category: string;
          code: string;
          name: string;
          brand: string | null;
          description: string | null;
          unit: string;
          cost_price: number;
          selling_price: number;
          stock_quantity: number;
          min_stock_level: number;
          is_for_sale: boolean;
          is_for_internal_use: boolean;
          tax_rate: number;
          image_url: string | null;
          sort_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          category: string;
          code: string;
          name: string;
          brand?: string | null;
          description?: string | null;
          unit?: string;
          cost_price?: number;
          selling_price?: number;
          stock_quantity?: number;
          min_stock_level?: number;
          is_for_sale?: boolean;
          is_for_internal_use?: boolean;
          tax_rate?: number;
          image_url?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          category?: string;
          code?: string;
          name?: string;
          brand?: string | null;
          description?: string | null;
          unit?: string;
          cost_price?: number;
          selling_price?: number;
          stock_quantity?: number;
          min_stock_level?: number;
          is_for_sale?: boolean;
          is_for_internal_use?: boolean;
          tax_rate?: number;
          image_url?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      materials: {
        Row: {
          id: string;
          company_id: string;
          category: string;
          code: string;
          name: string;
          brand: string | null;
          description: string | null;
          unit: string;
          cost_price: number;
          stock_quantity: number;
          min_stock_level: number;
          image_url: string | null;
          sort_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          category: string;
          code: string;
          name: string;
          brand?: string | null;
          description?: string | null;
          unit?: string;
          cost_price?: number;
          stock_quantity?: number;
          min_stock_level?: number;
          image_url?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          category?: string;
          code?: string;
          name?: string;
          brand?: string | null;
          description?: string | null;
          unit?: string;
          cost_price?: number;
          stock_quantity?: number;
          min_stock_level?: number;
          image_url?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      tags: {
        Row: {
          id: string;
          company_id: string;
          name: string;
          color: string | null;
          icon: string | null;
          parent_id: string | null;
          applicable_to: Json;
          sort_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          name: string;
          color?: string | null;
          icon?: string | null;
          parent_id?: string | null;
          applicable_to?: Json;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          name?: string;
          color?: string | null;
          icon?: string | null;
          parent_id?: string | null;
          applicable_to?: Json;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      tag_items: {
        Row: {
          id: string;
          tag_id: string;
          entity_type: string;
          entity_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          tag_id: string;
          entity_type: string;
          entity_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          tag_id?: string;
          entity_type?: string;
          entity_id?: string;
          created_at?: string;
        };
      };
      reservations: {
        Row: {
          id: string;
          company_id: string;
          store_id: string;
          customer_id: string | null;
          staff_id: string | null;
          menu_ids: Json;
          start_time: string;
          end_time: string;
          status: string;
          nomination_type: string;
          customer_name: string | null;
          customer_phone: string | null;
          customer_email: string | null;
          notes: string | null;
          source: string;
          external_id: string | null;
          reminder_sent_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          store_id: string;
          customer_id?: string | null;
          staff_id?: string | null;
          menu_ids?: Json;
          start_time: string;
          end_time: string;
          status?: string;
          nomination_type?: string;
          customer_name?: string | null;
          customer_phone?: string | null;
          customer_email?: string | null;
          notes?: string | null;
          source?: string;
          external_id?: string | null;
          reminder_sent_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          store_id?: string;
          customer_id?: string | null;
          staff_id?: string | null;
          menu_ids?: Json;
          start_time?: string;
          end_time?: string;
          status?: string;
          nomination_type?: string;
          customer_name?: string | null;
          customer_phone?: string | null;
          customer_email?: string | null;
          notes?: string | null;
          source?: string;
          external_id?: string | null;
          reminder_sent_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      visits: {
        Row: {
          id: string;
          company_id: string;
          store_id: string;
          customer_id: string;
          reservation_id: string | null;
          staff_id: string;
          nomination_type: string;
          check_in_at: string;
          service_start_at: string | null;
          service_end_at: string | null;
          check_out_at: string | null;
          status: string;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          store_id: string;
          customer_id: string;
          reservation_id?: string | null;
          staff_id: string;
          nomination_type?: string;
          check_in_at?: string;
          service_start_at?: string | null;
          service_end_at?: string | null;
          check_out_at?: string | null;
          status?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          store_id?: string;
          customer_id?: string;
          reservation_id?: string | null;
          staff_id?: string;
          nomination_type?: string;
          check_in_at?: string;
          service_start_at?: string | null;
          service_end_at?: string | null;
          check_out_at?: string | null;
          status?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      sales: {
        Row: {
          id: string;
          company_id: string;
          store_id: string;
          visit_id: string | null;
          customer_id: string | null;
          sale_number: string;
          sale_date: string;
          subtotal: number;
          discount_total: number;
          tax_total: number;
          total: number;
          points_used: number;
          points_earned: number;
          status: string;
          notes: string | null;
          created_by: string | null;
          voided_at: string | null;
          voided_by: string | null;
          void_reason: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          store_id: string;
          visit_id?: string | null;
          customer_id?: string | null;
          sale_number: string;
          sale_date?: string;
          subtotal?: number;
          discount_total?: number;
          tax_total?: number;
          total?: number;
          points_used?: number;
          points_earned?: number;
          status?: string;
          notes?: string | null;
          created_by?: string | null;
          voided_at?: string | null;
          voided_by?: string | null;
          void_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          store_id?: string;
          visit_id?: string | null;
          customer_id?: string | null;
          sale_number?: string;
          sale_date?: string;
          subtotal?: number;
          discount_total?: number;
          tax_total?: number;
          total?: number;
          points_used?: number;
          points_earned?: number;
          status?: string;
          notes?: string | null;
          created_by?: string | null;
          voided_at?: string | null;
          voided_by?: string | null;
          void_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      sale_items: {
        Row: {
          id: string;
          sale_id: string;
          item_type: string;
          item_id: string | null;
          name: string;
          quantity: number;
          unit_price: number;
          hair_length: string | null;
          hair_length_charge: number;
          discount_amount: number;
          tax_rate: number;
          tax_amount: number;
          subtotal: number;
          nomination_type: string | null;
          nomination_fee: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          sale_id: string;
          item_type: string;
          item_id?: string | null;
          name: string;
          quantity?: number;
          unit_price: number;
          hair_length?: string | null;
          hair_length_charge?: number;
          discount_amount?: number;
          tax_rate?: number;
          tax_amount?: number;
          subtotal?: number;
          nomination_type?: string | null;
          nomination_fee?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          sale_id?: string;
          item_type?: string;
          item_id?: string | null;
          name?: string;
          quantity?: number;
          unit_price?: number;
          hair_length?: string | null;
          hair_length_charge?: number;
          discount_amount?: number;
          tax_rate?: number;
          tax_amount?: number;
          subtotal?: number;
          nomination_type?: string | null;
          nomination_fee?: number;
          created_at?: string;
        };
      };
      sale_item_staff_assignments: {
        Row: {
          id: string;
          sale_item_id: string;
          staff_id: string;
          role: string;
          sales_ratio: number;
          sales_amount: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          sale_item_id: string;
          staff_id: string;
          role?: string;
          sales_ratio?: number;
          sales_amount?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          sale_item_id?: string;
          staff_id?: string;
          role?: string;
          sales_ratio?: number;
          sales_amount?: number;
          created_at?: string;
        };
      };
      sale_item_process_assignments: {
        Row: {
          id: string;
          sale_item_id: string;
          process_id: string;
          staff_id: string;
          productivity_ratio: number;
          productivity_amount: number;
          duration_minutes: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          sale_item_id: string;
          process_id: string;
          staff_id: string;
          productivity_ratio?: number;
          productivity_amount?: number;
          duration_minutes?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          sale_item_id?: string;
          process_id?: string;
          staff_id?: string;
          productivity_ratio?: number;
          productivity_amount?: number;
          duration_minutes?: number | null;
          created_at?: string;
        };
      };
      sale_payments: {
        Row: {
          id: string;
          sale_id: string;
          payment_method: string;
          amount: number;
          reference_number: string | null;
          stripe_payment_intent_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          sale_id: string;
          payment_method: string;
          amount: number;
          reference_number?: string | null;
          stripe_payment_intent_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          sale_id?: string;
          payment_method?: string;
          amount?: number;
          reference_number?: string | null;
          stripe_payment_intent_id?: string | null;
          created_at?: string;
        };
      };
      sale_discounts: {
        Row: {
          id: string;
          sale_id: string;
          sale_item_id: string | null;
          discount_type: string;
          discount_source: string;
          source_id: string | null;
          name: string;
          value: number;
          value_type: string;
          amount: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          sale_id: string;
          sale_item_id?: string | null;
          discount_type: string;
          discount_source: string;
          source_id?: string | null;
          name: string;
          value: number;
          value_type?: string;
          amount?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          sale_id?: string;
          sale_item_id?: string | null;
          discount_type?: string;
          discount_source?: string;
          source_id?: string | null;
          name?: string;
          value?: number;
          value_type?: string;
          amount?: number;
          created_at?: string;
        };
      };
      refunds: {
        Row: {
          id: string;
          company_id: string;
          sale_id: string;
          refund_number: string;
          refund_type: string;
          amount: number;
          reason: string | null;
          items: Json;
          created_by: string | null;
          approved_by: string | null;
          approved_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          sale_id: string;
          refund_number: string;
          refund_type?: string;
          amount: number;
          reason?: string | null;
          items?: Json;
          created_by?: string | null;
          approved_by?: string | null;
          approved_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          sale_id?: string;
          refund_number?: string;
          refund_type?: string;
          amount?: number;
          reason?: string | null;
          items?: Json;
          created_by?: string | null;
          approved_by?: string | null;
          approved_at?: string | null;
          created_at?: string;
        };
      };
      accounts_receivable: {
        Row: {
          id: string;
          company_id: string;
          sale_id: string;
          customer_id: string;
          amount: number;
          due_date: string | null;
          paid_amount: number;
          status: string;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          sale_id: string;
          customer_id: string;
          amount: number;
          due_date?: string | null;
          paid_amount?: number;
          status?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          sale_id?: string;
          customer_id?: string;
          amount?: number;
          due_date?: string | null;
          paid_amount?: number;
          status?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      tickets: {
        Row: {
          id: string;
          company_id: string;
          customer_id: string;
          ticket_type: string;
          name: string;
          total_uses: number;
          remaining_uses: number;
          total_amount: number | null;
          remaining_amount: number | null;
          applicable_menu_ids: Json;
          valid_from: string;
          valid_until: string | null;
          purchase_sale_id: string | null;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          customer_id: string;
          ticket_type: string;
          name: string;
          total_uses?: number;
          remaining_uses?: number;
          total_amount?: number | null;
          remaining_amount?: number | null;
          applicable_menu_ids?: Json;
          valid_from?: string;
          valid_until?: string | null;
          purchase_sale_id?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          customer_id?: string;
          ticket_type?: string;
          name?: string;
          total_uses?: number;
          remaining_uses?: number;
          total_amount?: number | null;
          remaining_amount?: number | null;
          applicable_menu_ids?: Json;
          valid_from?: string;
          valid_until?: string | null;
          purchase_sale_id?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      ticket_usages: {
        Row: {
          id: string;
          ticket_id: string;
          sale_id: string;
          sale_item_id: string | null;
          amount_used: number | null;
          uses_count: number;
          used_at: string;
        };
        Insert: {
          id?: string;
          ticket_id: string;
          sale_id: string;
          sale_item_id?: string | null;
          amount_used?: number | null;
          uses_count?: number;
          used_at?: string;
        };
        Update: {
          id?: string;
          ticket_id?: string;
          sale_id?: string;
          sale_item_id?: string | null;
          amount_used?: number | null;
          uses_count?: number;
          used_at?: string;
        };
      };
      coupons: {
        Row: {
          id: string;
          company_id: string;
          code: string;
          name: string;
          description: string | null;
          discount_type: string;
          discount_value: number;
          min_purchase_amount: number | null;
          max_discount_amount: number | null;
          applicable_menu_ids: Json;
          valid_from: string;
          valid_until: string | null;
          max_uses: number | null;
          used_count: number;
          is_single_use: boolean;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          code: string;
          name: string;
          description?: string | null;
          discount_type?: string;
          discount_value: number;
          min_purchase_amount?: number | null;
          max_discount_amount?: number | null;
          applicable_menu_ids?: Json;
          valid_from?: string;
          valid_until?: string | null;
          max_uses?: number | null;
          used_count?: number;
          is_single_use?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          code?: string;
          name?: string;
          description?: string | null;
          discount_type?: string;
          discount_value?: number;
          min_purchase_amount?: number | null;
          max_discount_amount?: number | null;
          applicable_menu_ids?: Json;
          valid_from?: string;
          valid_until?: string | null;
          max_uses?: number | null;
          used_count?: number;
          is_single_use?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      coupon_usages: {
        Row: {
          id: string;
          coupon_id: string;
          customer_id: string | null;
          sale_id: string;
          discount_amount: number;
          used_at: string;
        };
        Insert: {
          id?: string;
          coupon_id: string;
          customer_id?: string | null;
          sale_id: string;
          discount_amount: number;
          used_at?: string;
        };
        Update: {
          id?: string;
          coupon_id?: string;
          customer_id?: string | null;
          sale_id?: string;
          discount_amount?: number;
          used_at?: string;
        };
      };
      point_transactions: {
        Row: {
          id: string;
          company_id: string;
          customer_id: string;
          sale_id: string | null;
          transaction_type: string;
          points: number;
          balance_after: number;
          description: string | null;
          expires_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          customer_id: string;
          sale_id?: string | null;
          transaction_type: string;
          points: number;
          balance_after: number;
          description?: string | null;
          expires_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          customer_id?: string;
          sale_id?: string | null;
          transaction_type?: string;
          points?: number;
          balance_after?: number;
          description?: string | null;
          expires_at?: string | null;
          created_at?: string;
        };
      };
      shifts: {
        Row: {
          id: string;
          company_id: string;
          store_id: string;
          staff_id: string;
          shift_date: string;
          start_time: string;
          end_time: string;
          break_minutes: number;
          status: string;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          store_id: string;
          staff_id: string;
          shift_date: string;
          start_time: string;
          end_time: string;
          break_minutes?: number;
          status?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          store_id?: string;
          staff_id?: string;
          shift_date?: string;
          start_time?: string;
          end_time?: string;
          break_minutes?: number;
          status?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      attendances: {
        Row: {
          id: string;
          company_id: string;
          store_id: string;
          staff_id: string;
          shift_id: string | null;
          attendance_date: string;
          clock_in: string | null;
          clock_out: string | null;
          break_start: string | null;
          break_end: string | null;
          total_break_minutes: number;
          actual_work_minutes: number | null;
          status: string;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          store_id: string;
          staff_id: string;
          shift_id?: string | null;
          attendance_date: string;
          clock_in?: string | null;
          clock_out?: string | null;
          break_start?: string | null;
          break_end?: string | null;
          total_break_minutes?: number;
          actual_work_minutes?: number | null;
          status?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          store_id?: string;
          staff_id?: string;
          shift_id?: string | null;
          attendance_date?: string;
          clock_in?: string | null;
          clock_out?: string | null;
          break_start?: string | null;
          break_end?: string | null;
          total_break_minutes?: number;
          actual_work_minutes?: number | null;
          status?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      conversation_recordings: {
        Row: {
          id: string;
          company_id: string;
          visit_id: string;
          customer_id: string;
          staff_id: string;
          audio_url: string;
          duration_seconds: number;
          status: string;
          recorded_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          visit_id: string;
          customer_id: string;
          staff_id: string;
          audio_url: string;
          duration_seconds?: number;
          status?: string;
          recorded_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          visit_id?: string;
          customer_id?: string;
          staff_id?: string;
          audio_url?: string;
          duration_seconds?: number;
          status?: string;
          recorded_at?: string;
          created_at?: string;
        };
      };
      conversation_transcripts: {
        Row: {
          id: string;
          recording_id: string;
          full_text: string;
          segments: Json;
          language: string;
          confidence: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          recording_id: string;
          full_text: string;
          segments?: Json;
          language?: string;
          confidence?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          recording_id?: string;
          full_text?: string;
          segments?: Json;
          language?: string;
          confidence?: number | null;
          created_at?: string;
        };
      };
      conversation_analyses: {
        Row: {
          id: string;
          transcript_id: string;
          customer_id: string;
          topics: Json;
          sentiment: Json;
          keywords: Json;
          customer_preferences: Json;
          concerns: Json;
          opportunities: Json;
          summary: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          transcript_id: string;
          customer_id: string;
          topics?: Json;
          sentiment?: Json;
          keywords?: Json;
          customer_preferences?: Json;
          concerns?: Json;
          opportunities?: Json;
          summary?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          transcript_id?: string;
          customer_id?: string;
          topics?: Json;
          sentiment?: Json;
          keywords?: Json;
          customer_preferences?: Json;
          concerns?: Json;
          opportunities?: Json;
          summary?: string | null;
          created_at?: string;
        };
      };
      ai_suggestions: {
        Row: {
          id: string;
          company_id: string;
          customer_id: string;
          visit_id: string | null;
          analysis_id: string | null;
          suggestion_type: string;
          title: string;
          description: string;
          confidence: number;
          priority: number;
          suggested_items: Json;
          timing: string;
          status: string;
          staff_response: string | null;
          outcome: string | null;
          expires_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          customer_id: string;
          visit_id?: string | null;
          analysis_id?: string | null;
          suggestion_type: string;
          title: string;
          description: string;
          confidence?: number;
          priority?: number;
          suggested_items?: Json;
          timing?: string;
          status?: string;
          staff_response?: string | null;
          outcome?: string | null;
          expires_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          customer_id?: string;
          visit_id?: string | null;
          analysis_id?: string | null;
          suggestion_type?: string;
          title?: string;
          description?: string;
          confidence?: number;
          priority?: number;
          suggested_items?: Json;
          timing?: string;
          status?: string;
          staff_response?: string | null;
          outcome?: string | null;
          expires_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      hairstyle_simulations: {
        Row: {
          id: string;
          company_id: string;
          customer_id: string;
          visit_id: string | null;
          source_image_url: string;
          reference_image_url: string | null;
          reference_source: string | null;
          reference_id: string | null;
          generated_image_url: string | null;
          parameters: Json;
          status: string;
          customer_rating: number | null;
          customer_feedback: string | null;
          staff_approved: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          customer_id: string;
          visit_id?: string | null;
          source_image_url: string;
          reference_image_url?: string | null;
          reference_source?: string | null;
          reference_id?: string | null;
          generated_image_url?: string | null;
          parameters?: Json;
          status?: string;
          customer_rating?: number | null;
          customer_feedback?: string | null;
          staff_approved?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          customer_id?: string;
          visit_id?: string | null;
          source_image_url?: string;
          reference_image_url?: string | null;
          reference_source?: string | null;
          reference_id?: string | null;
          generated_image_url?: string | null;
          parameters?: Json;
          status?: string;
          customer_rating?: number | null;
          customer_feedback?: string | null;
          staff_approved?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      notification_templates: {
        Row: {
          id: string;
          company_id: string;
          name: string;
          type: string;
          channel: string;
          subject: string | null;
          body: string;
          variables: Json;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          name: string;
          type: string;
          channel: string;
          subject?: string | null;
          body: string;
          variables?: Json;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          name?: string;
          type?: string;
          channel?: string;
          subject?: string | null;
          body?: string;
          variables?: Json;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      notifications: {
        Row: {
          id: string;
          company_id: string;
          template_id: string | null;
          recipient_type: string;
          recipient_id: string;
          channel: string;
          subject: string | null;
          body: string;
          data: Json;
          status: string;
          sent_at: string | null;
          read_at: string | null;
          error: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          template_id?: string | null;
          recipient_type: string;
          recipient_id: string;
          channel: string;
          subject?: string | null;
          body: string;
          data?: Json;
          status?: string;
          sent_at?: string | null;
          read_at?: string | null;
          error?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          template_id?: string | null;
          recipient_type?: string;
          recipient_id?: string;
          channel?: string;
          subject?: string | null;
          body?: string;
          data?: Json;
          status?: string;
          sent_at?: string | null;
          read_at?: string | null;
          error?: string | null;
          created_at?: string;
        };
      };
      subscriptions: {
        Row: {
          id: string;
          company_id: string;
          stripe_subscription_id: string;
          stripe_price_id: string;
          plan: string;
          status: string;
          current_period_start: string;
          current_period_end: string;
          cancel_at: string | null;
          canceled_at: string | null;
          trial_start: string | null;
          trial_end: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          stripe_subscription_id: string;
          stripe_price_id: string;
          plan: string;
          status?: string;
          current_period_start: string;
          current_period_end: string;
          cancel_at?: string | null;
          canceled_at?: string | null;
          trial_start?: string | null;
          trial_end?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          stripe_subscription_id?: string;
          stripe_price_id?: string;
          plan?: string;
          status?: string;
          current_period_start?: string;
          current_period_end?: string;
          cancel_at?: string | null;
          canceled_at?: string | null;
          trial_start?: string | null;
          trial_end?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      audit_logs: {
        Row: {
          id: string;
          company_id: string;
          user_id: string | null;
          staff_id: string | null;
          action: string;
          entity_type: string;
          entity_id: string | null;
          old_values: Json;
          new_values: Json;
          ip_address: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          user_id?: string | null;
          staff_id?: string | null;
          action: string;
          entity_type: string;
          entity_id?: string | null;
          old_values?: Json;
          new_values?: Json;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          user_id?: string | null;
          staff_id?: string | null;
          action?: string;
          entity_type?: string;
          entity_id?: string | null;
          old_values?: Json;
          new_values?: Json;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];
export type InsertTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];
export type UpdateTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update'];
